### PR TITLE
Apply temporary fix to hystrix configuration to use calling thread, a…

### PR DESCRIPTION
**Pull request by objectiser**
…s otherwise trace context for outbound request is lost

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay This provides a temp fix for the issue by making sure the outbound call from hystrix is in the same thread. Will raise a jira on camel-opentracing to provide a more appropriate fix longer term.

**Comment by objectiser** [comment]
https://issues.apache.org/jira/browse/CAMEL-11198

**Comment by pavolloffay** [comment]
cool thanks! Could you please attach screen shots similar to https://github.com/redhat-helloworld-msa/api-gateway/pull/13.

**Comment by objectiser** [comment]
msa-api-gw-jaeger

**Comment by objectiser** [comment]
msa-api-gw-jaeger-traces

**Comment by pavolloffay** [comment]
It looks nice :+1: Looking forward to test it. It seems that instrumentation creates more spans than camel-zipkin

**Comment by pavolloffay** [comment]
Thanks :+1:

**Comment by objectiser** [comment]
@pavolloffay Yes, there are additional spans due to the internal communication being performed by the camel route using the 'direct' connector.

**Pull request merged**
